sudo: required
services:
- docker
language: bash
script:
# register qemu-*-static for all supported processors except the current one
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# generate platform-specific Dockerfile
- ./generate-dockerfiles.sh
# build platform-specific Docker images
- docker build -f Dockerfile.amd64 -t sebastianalbers/privoxy:latest-amd64 .
- docker build -f Dockerfile.arm32v7 -t sebastianalbers/privoxy:latest-arm32v7 .
- docker build -f Dockerfile.arm64v8 -t sebastianalbers/privoxy:latest-arm64v8 .
# test platform-specific Docker images
- ./read-version.sh amd64
- ./read-version.sh arm32v7
- ./read-version.sh arm64v8
after_success:
# trigger build on Docker Hub
- curl -X POST "${DOCKER_HUB_TRIGGER_URL}"
