sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t sebastianalbers/rpi-privoxy .
# test image
- docker run sebastianalbers/rpi-privoxy /usr/sbin/privoxy --version
after_success:
# notify Docker Hub to make a new build
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    curl --data build=true -X POST "$DOCKER_HUB_TRIGGER_URL"
  fi
